modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
logoFile="no.png" #optional
[[mods]] #mandatory
modId="cleanchatmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Clean Chat Mod" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/steffenjacobs/minecraft-cleanchat-mod" #optional
authors="Steffen Jacobs" #optional
description='''
This mod automatically hides the serverside voting reminder message.
'''
